FROM python:3.12.7-slim-bookworm

RUN apt-get update && apt-get install -y build-essential python3-dev
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uwsgi", "uwsgi.ini"]